Il existe 2 approches :

- "Piloté par le template" : on écrit le formulaire en utilisant seulement des directives (utile pour des formulaires simples, sans trop de validation).
- "Piloté par le code" : on écrit une description du formulaire dans le composant, puis on utilise des directives pour lier ce formulaire aux champs (plus puissant pour faire de la validation, générer des formulaires dynamiques, ...).

=== `FormControl`

NOTE: Le `FormControl` est la plus petite partie d'un formulaire. Il encapsule l'état du champ et sa valeur.

`FormControl` a plusieurs attributs et méthodes :

|===
| `valid` / `invalid`       | Si le champ est valide ou invalide au regard des contraintes imposées.
| `errors`                  | Est un objet qui contient les erreurs du champ .
| `dirty` / `pristine`      | Respectivement `false` & `true` jusqu'à ce que l'utilisateur modifie la valeur du champ.
| `touched` / `untouched`   | Respectivement `false` & `true` jusqu'à ce que l'utilisateur soit entrée dans le champ.
| `value`                   | La valeur du champ.
| `valueChanges`            | Un observable qui émet à chaque changement sur le champ.
| `hasError()`              | Pour savoir si le contrôle a une erreur de donnée.
|===

Exemple :

[source,javascript]
----
const password = new FormControl();
console.log(password.dirty);
console.log(password.value);
console.log(password.hasError('required'));
----

=== `FormGroup`

NOTE: Les `FormControl` peuvent être regroupés en `FormGroup`, pour constituer une partie du formulaire qui a des règles de validations communes.

`FormGroup` a quasiment les mêmes attributs et méthodes qu'un `FormControl`:

|===
| `valid` / `invalid`       | Respectivement à `true` si tous les champs sont valides, et à `false` si un seul champ est invalide au regard des contraintes imposées.
| `errors`                  | Est un objet qui contient les erreurs du groupe. 
| `dirty` / `pristine`      | Respectivement `false` & `true` jusqu'à ce que l'utilisateur modifie la valeur d'un champ du groupe.
| `touched` / `untouched`   | Respectivement `false` & `true` jusqu'à ce que l'utilisateur soit entrée dans dans un champ du groupe.
| `value`                   | Les valeurs du groupe.
| `valueChanges`            | Un observable qui émet à chaque changement sur un contrôle du groupe.
| `hasError()`              | Pour savoir si le groupe a une erreur de donnée.
| `get()`                   | Pour récupérer un contrôle du groupe.
|===

Exemple : 

[source,javascript]
----
const form = new FormGroup({
  username: new FormControl('Cédric'),
  password: new FormControl()
});
console.log(form.dirty); // "false"
console.log(form.value); // "{username: "Cédric", password: null}"
console.log(form.get('username'));
----

=== Formulaire piloté par le template 

NOTE: Avec cette méthode, c'est le framework qui construit les instances de `FormControl` et `FormGroup`.

[source,javascript]
----
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms'; <1>

@NgModule({
  imports: [BrowserModule, FormsModule], <1>
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {
}
----
<1> Pour "piloter par le template", il faut importer le module `FormsModule`.

Construction du formulaire :

[source,javascript]
----
import { Component } from '@angular/core';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html' <1>
})
export class RegisterFormComponent {
  register(user) { <2>
    // ...
  }
}
----
<1> `register-form.component.html` contiendra le formulaire du composant.
<2> `register()` sera appelé par le handler d'événement `ngSubmit` du template, avec la valeur du formulaire en paramètre.

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register(userForm.value)" #userForm="ngForm"> <1> <2>
  <div>
    <label>Username</label>
    <input name="username" ngModel> <3>
  </div>
  <div>
    <label>Password</label>
    <input type="password" name="password" ngModel> <3>
  </div>
  <button type="submit">Register</button> <4>
</form>
----
<1> On défini un handler d'événement `ngSubmit` qui appelera la méthode `register()` du composant `RegisterFormComponent`.
<2> On définie une variable `userForm` à laquelle on assigne l'objet `ngForm`.
<3> Les directives `ngModel` crée le `FormControl` et le `<form>` crée automatiquement le `FormGroup`. Il faut bien donner un `name` aux `input`.
<4> Il faut ajouter un bouton de soumission.

WARNING: Pour le moment c'est du binding uni-directionnel. Si on met à jour le champ, le modèle sera mis à jour, mais mettre à jour le modèle ne mettra pas à jour le champ.

==== Binding bi-directionnel 

Tout d'abord on crée une interface `UserModel` :

[source,javascript]
----
export interface UserModel {
  username: string;
  password: string;
}
----

On ajuste la méthode `register()` :

[source,javascript]
----
import { Component } from '@angular/core';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html' <1>
})
export class RegisterFormComponent {
  user: UserModel = { <2>
    username: '',
    password: ''
  };
  
  register() {
    console.log(this.user); <3>
  }
}
----
<1> `register-form.component.html` contiendra le formulaire du composant.
<2> `user` est défini à partir de l'interface `UserModel`.
<3> Maintenant, `register()` trace directement l'objet `user`.

On lie les champs du template au model :

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()"> <1> <2>
  <div>
    <label>Username</label>
    <input name="username" [(ngModel)]="user.username"> <3>
  </div>
  <div>
    <label>Password</label>
    <input type="password" name="password" [(ngModel)]="user.password"> <3>
  </div>
  <button type="submit">Register</button> <4>
</form>
----
<1> On conserve le handler d'événement `ngSubmit` qui appelera la méthode `register()` du composant `RegisterFormComponent`, mais sans transmettre de paramètre.
<2> On supprime la variable `userForm`.
<3> Les directives `ngModel` crée le `FormControl` et le `<form>` crée automatiquement le `FormGroup`. Il faut bien donner un `name` aux `input`. Les champs sont maintenant liés au model avec `[(ngModel)]`.
<4> Il faut conserver le bouton de soumission.

Que veut dire `[(ngModel)]` ? Les syntaxes suivantes sont équivalentes :

[source,html]
----
<input name="user.name" [(ngModel)]="user.name">
<input name="user.name" [ngModel]="user.name" (ngModelChange)="user.username = $event">
----

=== Formulaire piloter par le code

NOTE: pour manipuler directement les formulaires dans le code, il faut utiliser les abstractions `FormControl` et `FormGroup`.

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  userForm: FormGroup; <1>

  constructor(fb: FormBuilder) { <2>
    this.userForm = fb.group({ <3>
      username: '',
      password: ''
    });
  }

  register() {
    // ...
  }
}
----
<1> On crée la propriété `userForm`.
<2> `FormBuilder` est injectée dans le composant.
<3> On crée un `<form>` avec deux contrôles `username` & `password`.

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()" [formGroup]="userForm"> <1> <2>
  <div>
    <label>Username</label>
    <input formControlName="username"> <3>
  </div>
  <div>
    <label>Password</label>
    <input type="password" formControlName="password"> <3>
  </div>
  <button type="submit">Register</button> <4>
</form>
----
<1> On défini un handler d'événement `ngSubmit` qui appelera la méthode `register()` du composant `RegisterFormComponent`.
<2> Avec la directive `[formGroup]`, on relie le formulaire à l'objet `userForm` du composant.
<3> Chaque `input` reçoit la directive `formControlName` avec le nom du contrôle auquel il est relié.

IMPORTANT: Comme c'est une valeur qui est transmise et non une expression, on n'utilise pas les `[]` autour de `formControlName`.

TIP: Attention à la subtilité entre `constructor(fb: FormBuilder)` et `constructor(private fb: FormBuilder)`

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  userForm: FormGroup; <1>

  constructor(private fb: FormBuilder) { <2>
    this.userForm = this.fb.group({ <3>
      username: '',
      password: ''
    });
  }

  register() {
    // ...
  }
}
----


On peux mettre à jour la valeur d'un `FormControl` depuis le composant en utilisant la méthode `setValue()` :

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormControl } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html',
})
export class RegisterFormComponent {
  usernameCtrl: FormControl;
  passwordCtrl: FormControl;
  userForm: FormGroup;

  constructor(fb: FormBuilder) {
    this.usernameCtrl = fb.control('');
    this.passwordCtrl = fb.control('');
    this.userForm = fb.group({
      username: this.usernameCtrl,
      password: this.passwordCtrl
    });
  }

  reset() {
    this.usernameCtrl.setValue('');
    this.passwordCtrl.setValue('');
  }

  register() {
    console.log(this.userForm.value);
  }
}
----

=== La validation (pilotage par le code)

Liste de quelques validateurs fournis par le framework :

|===
| `Validators.required`     | Pour vérifier qu'un contrôle n'est pas vide.
| `Validators.minLength(n)` | Pour s'assurer que la valeur entrée a au moins _n_ caractrères.
| `Validators.maxLength(n)` | Pour s'assurer que la valeur entrée a au plus _n_ caractrères.
| `Validators.email()`      | Pour s'assurer que l'adresse email est valide.
| `Validators.min(n)`       | Pour s'assurer que la valeur entrée vaut au moin _n_.
| `Validators.max(n)`       | Pour s'assurer que la valeur entrée vaut au plus _n_.
| `Validators.pattern(p)`   | Pour s'assurer que la valeur entrée correspond à l'expression régulière _p_ définie.
|===

NOTE: Les validateurs peuvent être multiples, en passant un tableau.

Exemple : 

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html',
})
export class RegisterFormComponent {
  userForm: FormGroup;

  constructor(fb: FormBuilder) {
    this.userForm = fb.group({
      username: fb.control('', [Validators.required, Validators.minLength(3)]), <1> <2>
      password: fb.control('', Validators.required) <1>
    });
  }

  register() {
    console.log(this.userForm.value);
  }
}
----
<1> On ajoute le validator `required` sur chaque contrôle.
<2> On s'assure que le nom de l'utilisateur fait 3 caractères au minimum.

=== La validation (pilotage par le template)

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register(userForm.value)" #userForm="ngForm">
  <div>
    <label>Username</label>
    <input name="username" ngModel required minlength="3"> <1> <2>
  </div>
  <div>
    <label>Password</label>
    <input type="password" name="password" ngModel required> <1>
  </div>
  <button type="submit">Register</button>
</form>
----
<1> On ajoute le validator `required` sur chaque contrôle.
<2> On s'assure que le nom de l'utilisateur fait 3 caractères au minimum.

=== Erreurs et soumission (pilotage par le code)

[source,javascript]
----
@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  userForm: FormGroup;
  usernameCtrl: FormControl;
  passwordCtrl: FormControl;

  constructor(fb: FormBuilder) {
    this.usernameCtrl = fb.control('', Validators.required);
    this.passwordCtrl = fb.control('', Validators.required);

    this.userForm = fb.group({
      username: this.usernameCtrl,
      password: this.passwordCtrl
    });
  }

  register() {
    console.log(this.userForm.value);
  }
}
----

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()" [formGroup]="userForm">
  <div>
    <label>Username</label><input formControlName="username">
    <div *ngIf="usernameCtrl.dirty && usernameCtrl.hasError('required')">Username is required</div>
    <div *ngIf="usernameCtrl.dirty && usernameCtrl.hasError('minlength')">Username should be 3 characters min</div>
  </div>
  <div>
    <label>Password</label><input type="password" formControlName="password">
    <div *ngIf="passwordCtrl.dirty && passwordCtrl.hasError('required')">Password is required</div>
  </div>
  <button type="submit" [disabled]="userForm.invalid">Register</button> <1>
</form>
----
<1> On peut désactiver le bouton de soumission si le formulaire n'est pas valide, en liant `disabled` à la propriété `invalid` du `userForm`.

WARNING: TODO : Il faudrait rectifier ce code en suivant les principes du "clean code".

=== Erreurs et soumission (pilotage par le template)

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register(userForm.value)" #userForm="ngForm">
  <div>
    <label>Username</label>
    <input name="username" ngModel required #username="ngModel">
    <div *ngIf="username.dirty && username.hasError('required')">Username is required</div>
  </div>
  <div>
    <label>Password</label>
    <input type="password" name="password" ngModel required #password="ngModel">
    <div *ngIf="password.dirty && password.hasError('required')">Password is required</div>
  </div>
  <button type="submit" [disabled]="userForm.invalid">Register</button>
</form>
----

=== Style & CSS

NOTE: Angular ajoute et enlève automatiquement certaines classes CSS sur chaque champ et le formulaire. Ex : `ng-invalid`, `ng-valid`, `ng-dirty`, `ng-pristine`, `ng-touched`, `ng-untouched`, `ng-pending`, ...

=== Créer un validateur spécifique synchrone ou asynchrone (pilotage par le code)

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  usernameCtrl: FormControl;
  passwordCtrl: FormControl;
  birthdateCtrl: FormControl;
  userForm: FormGroup;

  static isOldEnough(control: FormControl) { <1>
    const birthDatePlus18 = new Date(control.value); <2>
    birthDatePlus18.setFullYear(birthDatePlus18.getFullYear() + 18);
    return birthDatePlus18 < new Date() ? null : { tooYoung: true }; <3>
  }
  
  isUsernameAvailable(control: AbstractControl) { <4>
    const username = control.value;
    return this.userService.isUsernameAvailable(username).pipe( <5>
      map(available => available ? null : { alreadyUsed: true })
    );
  }  

  constructor(fb: FormBuilder) {
    this.usernameCtrl = fb.control('',
      Validators.required,
      control => this.isUsernameAvailable(control)); <6>
      
    this.passwordCtrl = fb.control('', Validators.required);
    
    this.birthdateCtrl = fb.control('', [
      Validators.required,
      RegisterFormComponent.isOldEnough <7>
    ]);
    
    this.userForm = fb.group({
      username: this.usernameCtrl,
      password: this.passwordCtrl,
      birthdate: this.birthdateCtrl
    });
  }

  register() {
    console.log(this.userForm.value);
  }
}
----
<1> On crée une méthode static qui accepte un `FormControl`.
<2> On va tester la propriété `value` du `FormControl` transmis.
<3> On retourne un objet avec les erreurs, ou `null` si la valeur est valide.
<4> Le validateur asynchrone accède au service du composant `userService`.
<5> La méthode `isUsernameAvailable` du service renvoie un `Observable`: si le `username` est disponible, il émet `null`, sinon il émet un objet d'erreur avec la clé `alreadyUsed`.
<6> On applique le validateur asynchrone `this.isUsernameAvailable()` sur le champ `usernameCtrl` (la classe `ng-pending` est ajoutée dynamiquement au champ tant que le validateur n'a pas terminé son travail).
<7> On applique le validateur synchrone `RegisterFormComponent.isOldEnough()` sur le champ `birthdateCtrl`.

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()" [formGroup]="userForm">
  <!-- ... -->
  <div>
    <label>Birth date</label>
    <input type="date" formControlName="birthdate"> <1>
    <div *ngIf="birthdateCtrl.dirty">
      <div *ngIf="birthdateCtrl.hasError('required')">Birth date is required</div>
      <div *ngIf="birthdateCtrl.hasError('tooYoung')">You're way too young to be betting on pony races</div>
    </div>
  </div>
  <button type="submit" [disabled]="userForm.invalid">Register</button>
</form>
----
<1> On insère le champ `birthdate`.

=== Créer un validateur spécifique synchrone ou asynchrone (pilotage par le template)

TIP: Dans ce cas, le pilotage par le code est beaucoup plus simple...

=== Regrouper des champs

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  passwordForm: FormGroup;
  userForm: FormGroup;
  usernameCtrl: FormControl;
  passwordCtrl: FormControl;
  confirmCtrl: FormControl;

  static passwordMatch(group: FormGroup) { <1>
    const password = group.get('password').value;
    const confirm = group.get('confirm').value;
    return password === confirm ? null : { matchingError: true };
  }

  constructor(fb: FormBuilder) {
    this.usernameCtrl = fb.control('', Validators.required);
    this.passwordCtrl = fb.control('', Validators.required);
    this.confirmCtrl = fb.control('', Validators.required);

    this.passwordForm = fb.group(
      { password: this.passwordCtrl, confirm: this.confirmCtrl }, <2>
      { validator: RegisterFormComponent.passwordMatch } <3>
    );

    this.userForm = fb.group({
      username: this.usernameCtrl,
      passwordForm: this.passwordForm <4>
    });
  }

  register() {
    console.log(this.userForm.value);
  }
}
----
<1> On crée la méthode statique `passwordMatch` qui accepte un `formGroup`.
<2> On crée un nouveau groupe `passwordForm`, avec les deux champs.
<3> On ajoute le validateur `passwordMatch` au groupe `passwordForm`.
<4> Le groupe `passwordForm` est ajouté au groupe `userForm`.

On met à jour le template :

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()" [formGroup]="userForm">
  <!-- ... -->
  <div formGroupName="passwordForm"> <1>
    <div>
      <label>Password</label>
      <input type="password" formControlName="password">
      <div *ngIf="passwordCtrl.dirty && passwordCtrl.hasError('required')">
        Password is required
      </div>
    </div>
    <div>
      <label>Confirm password</label>
      <input type="password" formControlName="confirm">
      <div *ngIf="confirmCtrl.dirty && confirmCtrl.hasError('required')">
        Confirm your password
      </div>
    </div>
    <div *ngIf="passwordForm.dirty && passwordForm.hasError('matchingError')">
      Your password does not match
    </div>
  </div>
  <button type="submit" [disabled]="userForm.invalid">Register</button>
</form>
----
<1> On rattache le template au formulaire grâce à la directive `formGroupName`.

=== Réagir au modification

[source,javascript]
----
import { Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { debounceTime, distinctUntilChanged } from 'rxjs/operators'; <1>

@Component({
  selector: 'ns-register',
  templateUrl: 'register-form.component.html'
})
export class RegisterFormComponent {
  userForm: FormGroup;
  usernameCtrl: FormControl;
  passwordCtrl: FormControl;
  passwordStrength = 0; <2>

  constructor(fb: FormBuilder) {
    this.usernameCtrl = fb.control('', Validators.required);
    this.passwordCtrl = fb.control('', Validators.required);

    this.userForm = fb.group({
      username: this.usernameCtrl,
      password: this.passwordCtrl
    });

    // we subscribe to every password change
    this.passwordCtrl.valueChanges.pipe( <3>
      debounceTime(400), <4>
      distinctUntilChanged() <5>
    ).subscribe(newValue => this.passwordStrength = newValue.length); <6>
  }

  register() {
    console.log(this.userForm.value);
  }
}
----
<1> On importe bien `debounceTime` et `distinctUntilChanged`.
<2> On crée un attribut `passwordStrength` dans notre instance de composant.
<3> On peut réagir aux modifications du contrôle `passwordCtrl` grâce à l'_observable_ `valueChanges`.
<4> `debounceTime(400)` émettra des valeurs quand l'utilisateur aura arrêté de taper plus de 400ms.
<5> `distinctUntilChanged()` émettra des valeurs si la nouvelle valeur est différente de l'ancienne.
<6> On attribut à `passwordStrength` la nouvelle valeur.

On met à jour le template :

[source,html]
----
<h2>Sign up</h2>
<form (ngSubmit)="register()" [formGroup]="userForm">
  <!-- ... -->
  <div>
    <label>Password</label>
    <input type="password" formControlName="password">
    <div>Strength: {{ passwordStrength }}</div> <1>
    <div *ngIf="passwordCtrl.dirty && passwordCtrl.hasError('required')">
      Password is required
    </div>
  </div>
  <button type="submit" [disabled]="userForm.invalid">Register</button>
</form>
----
<1> On insère la valeur de `passwordStrength`.

=== Mettre à jour seulement à la perte de focus ou à la soumission

NOTE: Depuis Angular 5.0, on peut mettre à jour la valeur ou la validité d'un champ à la perte de focus (`blur`) ou à la soumission du formulaire (`submit`).

Pour cela, le constructeur de `FormControl` accepte un objet `options` en second paramètre ( qui permet de définir les validateurs synchrones et asynchrones). Voici les options de `updateOn` :

|===
| `change`  | (Valeur par défaut). Valeur et validité mises à jour à chaque changement.
| `blur`    | Valeur et validité mises à jour uniquement quand le champ perd le focus.
| `submit`  | Valeur et validité mises à jour uniquement quand le formulaire parent est soumis.
|===

Exemples :

[source,javascript]
----
this.usernameCtrl = new FormControl('', Validators.required);
this.passwordCtrl = new FormControl('', {
  validators: Validators.required,
  updateOn: 'blur' <1>
});
----
<1> Dans de cas, le contrôle `passwordCtrl` mettra à jour la valeur et la validité quand le champ perdra le focus.

[source,javascript]
----
this.userForm = new FormGroup({
  username: this.usernameCtrl,
  password: this.passwordCtrl
}, {
  updateOn: 'blur' <1>
});
----
<1> Dans ce cas, la configuration s'applique à tous les champs du groupe `userForm`.
