NOTE: L'injection de dépendances est un _design pattern_ : Le framework crée l'instance du service lui-même et la fournie au composant qui en a besoin.

Il faut d'abord rendre disponible son service à l'injection (Angular 6) :

[source,javascript]
----
import { Injectable } from '@angular/core';

@Injectable({ <1>
  providedIn: 'root' <2>
})
export class ApiService {
  get(path) {
    // todo: call the backend API
  }
}
----
<1> Depuis Angular 6, le décorateur `@Injectable` peut être utilisé pour rendre disponible `ApiService` à l'injection.
<2> `root` signifie que `ApiService` peut être utilisé partout.

IMPORTANT: Depuis Angular 6, il est recommandé d'utiliser le décorateur `@Injectable`

Avec une version d'Angular inférieure à la 6, la déclaration se fait ainsi :

[source,javascript]
----
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { ApiService } from './services/api.service';

@NgModule({
  imports: [BrowserModule],
  declarations: [AppComponent],
  providers: [ <1>
    ApiService
  ],
  bootstrap: [AppComponent]
})
export class AppModule {

}
----
<1> Avant Angular 6, il faut déclarer son service dans la propriété `providers` du décorateur `@NgModule` du module `AppModule`

On peut ensuite utiliser son service `ApiService` :

[source,javascript]
----
import { Injectable } from '@angular/core';
import { ApiService } from './api.service'; <1>

@Injectable({
  providedIn: 'root'
})
export class RaceService {
  constructor(private apiService: ApiService) { <2>
  }

  list() {
    return this.apiService.get('/races'); <3>
  }
}
----
<1> On peut maintenant importer `ApiService` ...
<2> ... Injecter `ApiService` dans le constructeur ...
<3> ... Et utiliser le service `ApiService`.

=== AppModule : la configuration des `providers`

En fait cette syntaxe raccourcie de la configuration des `providers` ... :

.src/app/app.module.ts
[source,javascript]
----
// ...

@NgModule({
  // ...
  providers: [
    ApiService
  ],
  // ...
})

// ...
----

Correspond à la version longue suivante :

[source,javascript]
----
// ...

@NgModule({
  // ...
  providers: [
    { provide: ApiService, useClass: ApiService } <1>
  ]
  // ...
})

// ...
----
<1> On indique à l'injecteur que nous voulons un _binding_ entre le token `ApiService` du `provide` et la classe `ApiService` du `useClass`.

TIP: On peut écrire la version raccourcie quand le token du `provide` et identique au  nom de la classe du `userClass`.

IMPORTANT: le token doit identifier de manière unique la dépendance.